### ISSUE TITLE
Trap Cooldown not recognized?

### ISSUE THREAD

**Issue by timtips** [max-arias/poeGems#1]
Given this input string and shadow as the selected class:
"arc multiple traps trap cluster traps trap and mine damage trap cooldown controlled destruction spark"

trap cooldown isn't recognized as a skill gem and is not added to the list.

Great tool, thanks for sharing :)

**Comment by max-arias** [comment]
Hey, thanks for the issue! Should be fixed now. :)

http://max-arias.github.io/poeGems/?found=81PS6LuPjhQtrrsLatmpTk
Clear

**Comment by timtips** [comment]
Thank you for fixing it :) Keep up the good work! :+1:
